[package]
name = "clasic-dungeon-game"
version = "0.1.1"
edition = "2021"
authors = ["Anton <mrpotato.04.contact@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
